locals {
  resource_group_name = element(split("/", var.resource_group_id), 4)

  databases = {
    for database_name, database in var.databases : database_name => {
      name           = database_name
      sku_name       = database.sku_name
      max_size_gb    = database.max_size_gb
      zone_redundant = database.zone_redundant
    }
  }

  private_endpoints = var.private_endpoint == null ? {} : {
    default = {
      subnet_resource_id            = var.private_endpoint.subnet_resource_id
      subresource_name              = "sqlServer"
      private_dns_zone_resource_ids = toset(var.private_endpoint.private_dns_zone_resource_ids)
      tags                          = var.tags
    }
  }
}

module "sql_server" {
  source  = "Azure/avm-res-sql-server/azurerm"
  version = "0.2.1"

  name                = var.name
  location            = var.location
  resource_group_name = local.resource_group_name
  tags                = var.tags
  server_version      = "12.0"

  # Secure defaults: Entra ID only, no SQL logins, private access.
  # A bootstrap password is still generated by the module (the provider requires one at creation),
  # kept in state as sensitive and never output; azuread_administrator.azuread_authentication_only
  # makes it unusable for sign-in.
  generate_administrator_login_password = true
  azuread_administrator = {
    azuread_authentication_only = true
    login_username              = var.entra_admin_login
    object_id                   = var.entra_admin_object_id
  }
  public_network_access_enabled = var.public_network_access_enabled

  databases         = local.databases
  private_endpoints = local.private_endpoints
  managed_identities = {
    system_assigned = var.enable_system_assigned_identity
  }
  role_assignments = var.role_assignments
}
